<?php

return array (
  'version' => '5.6.4',
  'title' => 'Regions',
  'type' => 'rfc_regions',
  'id' => '5fdbb49d840f9',
  'updated' => 1747761539,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '682cb9729a5e34' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Top Level Guide Page',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_682cb90d6fb92',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '682cb9729a5e34',
    ),
    '6478d5baffbe78' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Season Start',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_6478d2d944538',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6478d5baffbe78',
    ),
    '6478d75a2ed918' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Season Length',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_6478d34f44539',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6478d75a2ed918',
    ),
    '652ee929431270' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Primary',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_652ee8f6337f5',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '652ee929431270',
    ),
    '65f8917bf47ae0' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Image',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_65f89113d44f2',
      'image_size' => 'cpac-custom',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '65f8917bf47ae0',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);