<?php

return array (
  'version' => '5.6.4',
  'title' => 'Destinations',
  'type' => 'rfc_destinations',
  'id' => '5fdbb28b974a8',
  'updated' => 1671137516,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '',
      'width_unit' => '%',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '62f51c4b231270' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Latitude (S)',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_62ed72318a5d6',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '62f51c4b231270',
    ),
    '62f51c281ef9dc' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Longitude (W)',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_62ed724e8a5d7',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '62f51c281ef9dc',
    ),
    '638a56a3a0c49c' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Image',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_62f5318538a33',
      'image_size' => 'cpac-custom',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '638a56a3a0c49c',
    ),
    '639b88b0249ba4' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Is Crossing',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_6387c2f113254',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '639b88b0249ba4',
    ),
    '639b88be3e76c8' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Country Name',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_633f0e42059ad',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '639b88be3e76c8',
    ),
    '638a56b7851eb8' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Description',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_638a56679b389',
      'excerpt_length' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '638a56b7851eb8',
    ),
    '5fe12a9d773a9' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Activities',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5fe125b203346',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '5fe12a9d773a9',
    ),
    '5fdbb2c07cd7a' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Region',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5fc53363628e2',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '5fdbb2c07cd7a',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);