<?php

return array (
  'version' => '5.6.4',
  'title' => 'Destinations',
  'type' => 'rfc_destinations',
  'id' => '5fdbb28b974a8',
  'updated' => 1669841806,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '',
      'width_unit' => '%',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '62f5314e2d0e58' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Hero Image Portrait',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5fe125b203346',
      'export' => 'off',
      'name' => '62f5314e2d0e58',
    ),
    '62f51c281ef9dc' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Longitude',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_62ed724e8a5d7',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '62f51c281ef9dc',
    ),
    '62f51c4b231270' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Latitude',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_62ed72318a5d6',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '62f51c4b231270',
    ),
    '62f51c54683128' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Zoom Point Longitude',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_62ed728d8a5d9',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '62f51c54683128',
    ),
    '62f51c5e03d70c' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Zoom Point Latitude',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_62ed727b8a5d8',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '62f51c5e03d70c',
    ),
    '62f51d17a00000' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Zoom Level',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_62ed729a8a5da',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '62f51d17a00000',
    ),
    '5fe12a9d773a9' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Activities',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5fe125b203346',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '5fe12a9d773a9',
    ),
    '5fdbb2c07cd7a' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Region',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5fc53363628e2',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '5fdbb2c07cd7a',
    ),
    '6387c36a73b644' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Is Port',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_6387c2f113254',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6387c36a73b644',
    ),
    '6387c37bd374bc' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Country_Name_Short',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_633f0e52059ae',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6387c37bd374bc',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);