<?php

return array (
  'version' => '5.6.4',
  'title' => 'Regions',
  'type' => 'rfc_regions',
  'id' => '5fdbb49d840f9',
  'updated' => 1660235671,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '62f52f5bdfbe78' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Longitude',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_62ed762b1edf0',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '62f52f5bdfbe78',
    ),
    '62f52f7bd0624c' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Latitude',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_62ed761e1edef',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '62f52f7bd0624c',
    ),
    '62f52f833be76c' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Longitude Zoom Point',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_62f52f1546b5c',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '62f52f833be76c',
    ),
    '62f52f88e872b0' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Latitude Zoom Point',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_62f52efc46b5b',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '62f52f88e872b0',
    ),
    '62f52f8e8147b0' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Zoom Level',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_62f52f2b46b5d',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '62f52f8e8147b0',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);