<?php

return array (
  'version' => '5.6.4',
  'title' => 'Cruises',
  'type' => 'rfc_cruises',
  'id' => '5fdbe431766d9',
  'updated' => 1685636174,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '631a3f9da7ef9c' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Hero Gallery',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5f6b863fe1d13',
      'image_size' => 'cpac-custom',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'number_of_items' => '10',
      'export' => 'off',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => '631a3f9da7ef9c',
    ),
    '62e0669729fbe8' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Vessel Capacity',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_602bf5195119f',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '62e0669729fbe8',
    ),
    '60aeb31bf645a0' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Search Rank',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_60aeb050fa54f',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '60aeb31bf645a0',
    ),
    '6478c4131d70a4' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Top Snippet',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5f627996a57b4',
      'excerpt_length' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6478c4131d70a4',
    ),
    '6478c434b1a9fc' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Service Level',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_63efb5dda315b',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6478c434b1a9fc',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);