<?php

return array (
  'version' => '5.6.4',
  'title' => 'Destinations',
  'type' => 'rfc_destinations',
  'id' => '5fdbb28b974a8',
  'updated' => 1659729240,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '',
      'width_unit' => '%',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '5fdbb2c07cd75' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Navigation Title',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5fdbaeda25a3a',
      'character_limit' => '20',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '5fdbb2c07cd75',
    ),
    '62e0aa6b004188' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Feature Image',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_62e0aa2f56ad1',
      'image_size' => 'cpac-custom',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '62e0aa6b004188',
    ),
    '5fdbb2c07cd7a' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Region',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5fc53363628e2',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '5fdbb2c07cd7a',
    ),
    '5fea3ae22edd2' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Locations',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5fea3a88df109',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '5fea3ae22edd2',
    ),
    '5fe12a9d773a9' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Activities',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5fe125b203346',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '5fe12a9d773a9',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);