<?php

return array (
  'version' => '5.5.1',
  'title' => 'Tours',
  'type' => 'rfc_tours',
  'id' => '5fdce4309e743',
  'updated' => 1622062652,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '5fdce577c60ef' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Tour Name',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5f975c6168c7d',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '5fdce577c60ef',
    ),
    '5fdce577c60fa' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Length (Days)',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5fce65e403cb9',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '5fdce577c60fa',
    ),
    '5fdce46352681' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Destinations',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5f9735d666c72',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '5fdce46352681',
    ),
    '5fdce577c60fe' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Locations',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5fdce47a7322a',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '5fdce577c60fe',
    ),
    '5fe128b65b244' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Activities',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5fe1282229469',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '5fe128b65b244',
    ),
    '5fdce46352684' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Experiences',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5fce605f5e5ab',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '5fdce46352684',
    ),
    '60aeb61553f7d0' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Search Rank',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_60aeb24208df7',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '60aeb61553f7d0',
    ),
    '5fdce577c6105' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Best Selling',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5fcea1da5f0a3',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '5fdce577c6105',
    ),
    '6079c255220c48' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Best Selling Regional',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_6079c1c8a3ccc',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6079c255220c48',
    ),
    '60145e4406664' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Best Selling Image',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_60145dad8a75a',
      'image_size' => 'cpac-custom',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '60145e4406664',
    ),
    '5fdce577c6108' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Featured Image',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5f9735d66627b',
      'image_size' => 'cpac-custom',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '5fdce577c6108',
    ),
    '602bed36e4dd30' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Hotels',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_602ab8113ceda',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '602bed36e4dd30',
    ),
    '5fdce577c610a' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Hero Image',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_5f9735d665e90',
      'image_size' => 'cpac-custom',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '5fdce577c610a',
    ),
    '5fdce577c610d' => 
    array (
      'type' => 'column-author_name',
      'label' => 'Author',
      'width' => '',
      'width_unit' => '%',
      'display_author_as' => 'display_name',
      'user_link_to' => 'edit_user',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '5fdce577c610d',
    ),
    'date' => 
    array (
      'type' => 'date',
      'label' => 'Date',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'filter_format' => '',
      'name' => 'date',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);