<?php

return array (
  'version' => '5.4.2',
  'title' => 'Hotels',
  'type' => 'rfc_hotels',
  'id' => '602ab62840594',
  'updated' => 1614618256,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '',
      'width_unit' => '%',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '602ab62ee72b04' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Navigation Title',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_602aa9a59aad0',
      'character_limit' => '20',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '602ab62ee72b04',
    ),
    '602ab644f53f7c' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Featured Image',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_602aafe89aad1',
      'image_size' => 'cpac-custom',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '602ab644f53f7c',
    ),
    '602ab6594b020c' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Price Level',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_602aaffb9aad2',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '602ab6594b020c',
    ),
    '602ab66c80c49c' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Destinations',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_602ab5e0dbe48',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '602ab66c80c49c',
    ),
    '602ab678e978d4' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Locations',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_602ab602dbe49',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '602ab678e978d4',
    ),
    '602ab6999cac08' => 
    array (
      'type' => 'column-author_name',
      'label' => 'Author',
      'width' => '',
      'width_unit' => '%',
      'display_author_as' => 'display_name',
      'user_link_to' => 'edit_user',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '602ab6999cac08',
    ),
    'date' => 
    array (
      'type' => 'date',
      'label' => 'Date',
      'width' => '',
      'width_unit' => '%',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'filter_format' => '',
      'name' => 'date',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);