<?php

return array (
  'version' => '5.5.3',
  'title' => 'Experiences',
  'type' => 'rfc_experiences',
  'id' => '607f13a39d314',
  'updated' => 1625245615,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '607f13ac69fbe8' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Icon',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_607f137a22f59',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '607f13ac69fbe8',
    ),
    '60df47a309374c' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Include Cruises',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_60df47701c70a',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '60df47a309374c',
    ),
    'date' => 
    array (
      'type' => 'date',
      'label' => 'Date',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'filter_format' => '',
      'name' => 'date',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);