<?php

return array (
  'version' => '5.6.4',
  'title' => 'Deals',
  'type' => 'rfc_deals',
  'id' => '61dca42e9152d',
  'updated' => 1704815808,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '61dca3f7b374bc' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Navigation Title',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_61dc9f9d53590',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '61dca3f7b374bc',
    ),
    '643579a8feb850' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Short Title',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_6435757d240b9',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '643579a8feb850',
    ),
    '6440045f381064' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Category',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_61dc9f9d6d5d7',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6440045f381064',
    ),
    '643579931be76c' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Description',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_61dca7348a395',
      'excerpt_length' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'editable_type' => 'textarea',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '643579931be76c',
    ),
    '61dca405c8f5c4' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Featured Image',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_61dc9f9d56faa',
      'image_size' => 'cpac-custom',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '61dca405c8f5c4',
    ),
    '6453e0cfd8d4fc' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Has Expiry Date',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_64357469240b4',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6453e0cfd8d4fc',
    ),
    '6453e088249ba4' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Expiry Date',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_6435752d240b8',
      'date_format' => 'acf',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'filter_format' => '',
      'name' => '6453e088249ba4',
    ),
    '659d6c9298d4fc' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Has Activation Date',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_659d6c3514b44',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '659d6c9298d4fc',
    ),
    '659d6ca9683128' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Activation Date',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_659d6c4814b45',
      'date_format' => 'acf',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'filter_format' => '',
      'name' => '659d6ca9683128',
    ),
    '64494f36b78d50' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Is Special Departure',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_64494ebbc5e66',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '64494f36b78d50',
    ),
    '64e38984400000' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Search Rank',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_64e389172e5ac',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '64e38984400000',
    ),
    '61e9e66a6147b0' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Is Active',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_61e9e5cfbfa3b',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '61e9e66a6147b0',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);