<?php

return array (
  'version' => '5.6.4',
  'title' => 'Deals',
  'type' => 'rfc_deals',
  'id' => '61dca42e9152d',
  'updated' => 1681226225,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '61dca3f7b374bc' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Navigation Title',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_61dc9f9d53590',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '61dca3f7b374bc',
    ),
    '643579a8feb850' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Short Title',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_6435757d240b9',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '643579a8feb850',
    ),
    '643579931be76c' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Description',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_61dca7348a395',
      'excerpt_length' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'editable_type' => 'textarea',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '643579931be76c',
    ),
    '61dca405c8f5c4' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Featured Image',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_61dc9f9d56faa',
      'image_size' => 'cpac-custom',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '61dca405c8f5c4',
    ),
    '61dca50672b020' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Categories',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_61dc9f9d6d5d7',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '61dca50672b020',
    ),
    '61dca3e7d020c4' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Is Exclusive',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_61dca09f34c1b',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '61dca3e7d020c4',
    ),
    '61e9e65e06a7f0' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Value Rating',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_61e9e50cbfa39',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '61e9e65e06a7f0',
    ),
    '61e9e66a6147b0' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Is Active',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_61e9e5cfbfa3b',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '61e9e66a6147b0',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);