<?php

return array (
  'version' => '5.6.4',
  'title' => 'Itineraries',
  'type' => 'rfc_itineraries',
  'id' => '62f1a455bcdd8',
  'updated' => 1778175621,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '636556573a9fc0' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Display Name',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_635973242d242',
      'character_limit' => '20',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '636556573a9fc0',
    ),
    '648a23728d9168' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Supplier',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_648a233651915',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '648a23728d9168',
    ),
    '648a4906ddf3b8' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Fly Category',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_648a47a4d8e81',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '648a4906ddf3b8',
    ),
    '63655a640fdf3c' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Length In Nights',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_63655a3f4eafa',
      'number_format' => '',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '63655a640fdf3c',
    ),
    '62f1a434df3b64' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Hero Gallery',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_62b21d860955b',
      'image_size' => 'cpac-custom',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'number_of_items' => '10',
      'export' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => '62f1a434df3b64',
    ),
    '6384eb809c28f4' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Routes',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_6384e5c17c120',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6384eb809c28f4',
    ),
    '6384eb9a3be76c' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Styles',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_6384e58d7c11f',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6384eb9a3be76c',
    ),
    '6528615fce147c' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Search Rank',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_62b21d85eab87',
      'number_format' => '',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6528615fce147c',
    ),
    '69fcce1667ef9c' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Precalculated Last Update',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_69fcc93d41b10',
      'repeater_display' => 'subfield',
      'sub_field' => 'field_63863e8c084b0',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'before' => '',
      'after' => '',
      'separator' => 'comma',
      'export' => 'off',
      'name' => '69fcce1667ef9c',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);