<?php

return array (
  'version' => '5.6.4',
  'title' => 'Itineraries',
  'type' => 'rfc_itineraries',
  'id' => '62f1a455bcdd8',
  'updated' => 1663024101,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '62f1a434df3b64' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Hero Image',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_62b21d860955b',
      'image_size' => 'cpac-custom',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '62f1a434df3b64',
    ),
    '62f1a441810624' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Hero Image Portrait',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_62f1a15fe48ab',
      'image_size' => 'cpac-custom',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '62f1a441810624',
    ),
    '631fbb9d343958' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Embarkation Point',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_631f8bd5db3a2',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '631fbb9d343958',
    ),
    '631fbbb569ba60' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Disembarkation Point',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_631f8c08db3a3',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '631fbbb569ba60',
    ),
    'date' => 
    array (
      'type' => 'date',
      'label' => 'Date',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'filter_format' => '',
      'name' => 'date',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);