<?php

return array (
  'version' => '5.6.4',
  'title' => 'Cabins',
  'type' => 'rfc_cabins',
  'id' => '63655323eb134',
  'updated' => 1713545757,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '636553b3960418' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Ship',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_63596c41cde8d',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '636553b3960418',
    ),
    '636553505a9fc0' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Display Name',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_63596c159c9fe',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '636553505a9fc0',
    ),
    '6622a2089d2f1c' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Order',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_6622a0ddddcd5',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6622a2089d2f1c',
    ),
    '648a246a9020c4' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Supplier',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_648a24327c5c9',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '648a246a9020c4',
    ),
    '64493dc2cf5c28' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Quantity',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_636aeaccbdf63',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '64493dc2cf5c28',
    ),
    '636552ec29fbe8' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Images',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_63596ba542a4e',
      'image_size' => 'cpac-custom',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'number_of_items' => '10',
      'export' => 'off',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => '636552ec29fbe8',
    ),
    '6365536523d70c' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Beds',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_63596b9f42a4d',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6365536523d70c',
    ),
    '642d98015b22d0' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Amenities',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_642d94519f7d8',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '642d98015b22d0',
    ),
    '6365532596c8b4' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Capacity',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_636551accb56e',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6365532596c8b4',
    ),
    '636553846c49bc' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Description',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_63596b1c42a4b',
      'excerpt_length' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '636553846c49bc',
    ),
    '63693183a08314' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Is Single',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_6369315086c32',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '63693183a08314',
    ),
    '63beddaa4c0830' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Is Sharable',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_63bedd4ae1ed3',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '63beddaa4c0830',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);