<?php

return array (
  'version' => '5.6.4',
  'title' => 'Countries',
  'type' => 'rfc_countries',
  'id' => '655ce0267b277',
  'updated' => 1700585718,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '655ce0cf0ed918' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Short Name',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_655ce054af77c',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '655ce0cf0ed918',
    ),
    '655ce0c6153f7c' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Embarkation Zone',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_655ce06caf77d',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '655ce0c6153f7c',
    ),
    'date' => 
    array (
      'type' => 'date',
      'label' => 'Date',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'filter_format' => '',
      'name' => 'date',
    ),
    'post_type' => 
    array (
      'type' => 'post_type',
      'label' => 'Type',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'name' => 'post_type',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);