<?php

return array (
  'version' => '5.6.4',
  'title' => 'Authors',
  'type' => 'rfc_authors',
  'id' => '68c99ed525444',
  'updated' => 1758044962,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '68c99e920978d4' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Image',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_68c99e00ee5bf',
      'image_size' => 'cpac-custom',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '68c99e920978d4',
    ),
    '68c9a310a147b0' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Description',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_68c9a2dd08f02',
      'excerpt_length' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'editable_type' => 'textarea',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '68c9a310a147b0',
    ),
    '68c99eb38a3d70' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Website',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_68c99e28ee5c0',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '68c99eb38a3d70',
    ),
    '68c99ec390624c' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Twitter',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_68c99e33ee5c1',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '68c99ec390624c',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);