<?php

return array (
  'version' => '5.6.4',
  'title' => 'Optional Activities',
  'type' => 'rfc_opt_activities',
  'id' => '69a0a2a34b544',
  'updated' => 1772136025,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '69a0a5faa39580' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Display Title',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_69a0a0b1a0745',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '69a0a5faa39580',
    ),
    '69a0a61fce5604' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Price',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_69a0a074a0743',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '69a0a61fce5604',
    ),
    '69a0a637d7ced8' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Price Range To',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_69a0a083a0744',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '69a0a637d7ced8',
    ),
    '69a0a256a08314' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Image',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_69a0a0dfa0746',
      'image_size' => 'cpac-custom',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '69a0a256a08314',
    ),
    '69a0a264fdf3b8' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Supplier',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_69a09e84a0742',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '69a0a264fdf3b8',
    ),
    '69a0a293fdf3b8' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Description',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_69a0a0eca0747',
      'excerpt_length' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'editable_type' => 'textarea',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '69a0a293fdf3b8',
    ),
    '69a0a3b22ccccc' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Standard Activity',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_69a0a364f6510',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '69a0a3b22ccccc',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);