<?php

return array (
  'version' => '5.6.4',
  'title' => 'Extensions',
  'type' => 'rfc_extensions',
  'id' => '6a07612ee2d92',
  'updated' => 1778877786,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '',
      'width_unit' => '%',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    '6a0760af0b020c' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Display Name',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_6a075e648abc8',
      'character_limit' => '20',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6a0760af0b020c',
    ),
    '6a078542191688' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Price',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_6a07850713ef0',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6a078542191688',
    ),
    '6a07614818d4fc' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Length In Nights',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_6a075e649f388',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6a07614818d4fc',
    ),
    '6a0760e1578d50' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Embarkation Point',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_6a075e64ac171',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6a0760e1578d50',
    ),
    '6a0760caac8b44' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Disembarkation Point',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_6a075e64b02c2',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6a0760caac8b44',
    ),
    '6a0760f8a8b438' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Region',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_6a075e6481d0c',
      'post_property_display' => 'title',
      'post_link_to' => 'edit_post',
      'number_of_items' => '10',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6a0760f8a8b438',
    ),
    '6a07610a2c0830' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Hero Gallery',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_6a075e648db25',
      'image_size' => 'cpac-custom',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'number_of_items' => '10',
      'export' => 'off',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => '6a07610a2c0830',
    ),
    '6a07611c641894' => 
    array (
      'type' => 'column-acf_field',
      'label' => 'Search Rank',
      'width' => '',
      'width_unit' => '%',
      'field' => 'field_6a075e64f0cd2',
      'number_format' => '',
      'export' => 'off',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => '6a07611c641894',
    ),
  ),
  'settings' => 
  array (
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_new_inline' => 'on',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'sorting' => '0',
    'sorting_order' => 'asc',
  ),
);